import { useEffect, useRef, useState } from 'react'
import { createClient } from '@supabase/supabase-js'
import { Activity, ChevronRight, Copy, Crosshair, DoorOpen, Flame, LockKeyhole, LogOut, Radio, ShieldAlert, Skull, Sparkles, Users, Wifi, WifiOff, Zap } from 'lucide-react'
import { calculateRound } from './gameLogic'
import './App.css'

const ROUND_SECONDS = 30
const hasSupabase = Boolean(import.meta.env.VITE_SUPABASE_URL && import.meta.env.VITE_SUPABASE_ANON_KEY)
const supabase = hasSupabase ? createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_ANON_KEY) : null
const id = () => Math.random().toString(36).slice(2, 9)
const code = () => Math.floor(100000 + Math.random() * 900000).toString()
const randomChoice = () => Math.floor(Math.random() * 101)

export default function App() {
  const [view, setView] = useState('lobby'); const [name, setName] = useState(''); const [roomCode, setRoomCode] = useState(''); const [joinCode, setJoinCode] = useState(''); const [players, setPlayers] = useState([]); const [hostId, setHostId] = useState(''); const [playerId] = useState(id); const [phase, setPhase] = useState('lobby'); const [round, setRound] = useState(1); const [seconds, setSeconds] = useState(ROUND_SECONDS); const [choice, setChoice] = useState(50); const [locked, setLocked] = useState(false); const [choices, setChoices] = useState({}); const [summary, setSummary] = useState(null); const [gameOver, setGameOver] = useState(false); const channel = useRef(null); const current = useRef({})
  const me = players.find((player) => player.id === playerId); const isHost = hostId === playerId
  useEffect(() => { current.current = { players, hostId, phase, round, seconds, choices, summary } }, [players, hostId, phase, round, seconds, choices, summary])
  useEffect(() => {
    if (!roomCode || !supabase) return undefined
    const room = supabase.channel(`room_${roomCode}`, { config: { broadcast: { self: true }, presence: { key: playerId } } })
    room.on('broadcast', { event: 'state' }, ({ payload }) => hydrate(payload)).on('broadcast', { event: 'lock' }, ({ payload }) => setPlayers((list) => list.map((player) => player.id === payload.id ? { ...player, locked: true } : player))).on('broadcast', { event: 'join' }, ({ payload }) => { if (current.current.hostId === playerId && !current.current.players.some((player) => player.id === payload.player.id) && current.current.players.length < 5) { const next = [...current.current.players, payload.player]; setPlayers(next); sendState({ players: next }) } }).on('broadcast', { event: 'reveal' }, () => revealMyChoice()).on('broadcast', { event: 'choice' }, ({ payload }) => collectChoice(payload)).on('broadcast', { event: 'leave' }, ({ payload }) => setPlayers((list) => list.filter((player) => player.id !== payload.id))).on('presence', { event: 'sync' }, () => { if (isHost) sendState() }).subscribe(async (status) => { if (status === 'SUBSCRIBED') { await room.track({ id: playerId, name, active: true }); room.send({ type: 'broadcast', event: 'join', payload: { player: { id: playerId, name, points: 0, locked: false, dead: false, pending: null } } }) } })
    channel.current = room
    return () => { room.unsubscribe(); channel.current = null }
  }, [roomCode, playerId])
  useEffect(() => {
    if (!isHost || view !== 'game' || phase !== 'lock') return undefined
    const timer = setInterval(() => { const next = current.current.seconds - 1; if (next <= 0) { clearInterval(timer); requestReveal() } else { setSeconds(next); sendState({ seconds: next }) } }, 1000)
    return () => clearInterval(timer)
  }, [isHost, view, phase, round])
  function send(message) { channel.current?.send({ type: 'broadcast', ...message }) }
  function sendState(extra = {}) { send({ event: 'state', payload: { ...current.current, hostId, ...extra } }) }
  function hydrate(next) { if (!next) return; if (next.players) setPlayers(next.players); if (next.hostId) setHostId(next.hostId); if (next.phase) setPhase(next.phase); if (next.round) setRound(next.round); if (typeof next.seconds === 'number') setSeconds(next.seconds); if (next.choices) setChoices(next.choices); if (next.summary !== undefined) setSummary(next.summary) }
  function enterRoom(create) { const clean = name.trim().slice(0, 18); const room = create ? code() : joinCode.replace(/\D/g, ''); if (!clean || room.length !== 6) return; setRoomCode(room); setHostId(create ? playerId : ''); setPlayers([{ id: playerId, name: clean, points: 0, locked: false, dead: false, pending: null }]); setView('room') }
  function startGame() { const next = players.map((player) => ({ ...player, locked: false })); setPlayers(next); setPhase('lock'); setSeconds(ROUND_SECONDS); setView('game'); sendState({ players: next, phase: 'lock', seconds: ROUND_SECONDS, round, choices: {}, summary: null }) }
  function lock() { if (!me || me.dead || locked) return; const value = Math.max(0, Math.min(100, Number(choice) || 0)); const next = players.map((player) => player.id === playerId ? { ...player, locked: true, pending: value } : player); setLocked(true); setPlayers(next); send({ event: 'lock', payload: { id: playerId } }); if (isHost && next.filter((player) => !player.dead).every((player) => player.locked)) requestReveal() }
  function requestReveal() { if (phase !== 'lock') return; setPhase('reveal'); setChoices({}); sendState({ phase: 'reveal', choices: {} }); send({ event: 'reveal', payload: {} }); revealMyChoice() }
  function revealMyChoice() { const player = current.current.players.find((item) => item.id === playerId); if (player && !player.dead) send({ event: 'choice', payload: { id: playerId, value: player.pending ?? randomChoice() } }) }
  function collectChoice(payload) { setChoices((old) => { const next = { ...old, [payload.id]: payload.value }; const active = current.current.players.filter((player) => !player.dead); if (isHost && active.every((player) => next[player.id] !== undefined)) finish(next); return next }) }
  function finish(revealed = choices) { const active = current.current.players.filter((player) => !player.dead); const values = Object.fromEntries(active.map((player) => [player.id, revealed[player.id] ?? player.pending ?? randomChoice()])); const result = calculateRound(active, values); const next = current.current.players.map((player) => { const points = player.dead ? player.points : player.points + (result.penalties[player.id] ?? 0); return { ...player, points, dead: points <= -10, locked: false, pending: null } }); const resultWithState = { ...result, choices: values, players: next, round }; setPlayers(next); setSummary(resultWithState); setPhase('summary'); setLocked(false); sendState({ players: next, phase: 'summary', summary: resultWithState, choices: values }) }
  function nextRound() { const survivors = players.filter((player) => !player.dead); if (survivors.length <= 1) return setGameOver(true); const next = round + 1; setRound(next); setPhase('lock'); setSeconds(ROUND_SECONDS); setSummary(null); setChoices({}); setLocked(false); sendState({ round: next, phase: 'lock', seconds: ROUND_SECONDS, summary: null, choices: {} }) }
  function leave() { send({ event: 'leave', payload: { id: playerId } }); channel.current?.unsubscribe(); setView('lobby'); setRoomCode(''); setPlayers([]); setPhase('lobby') }
  if (view === 'lobby') return <Lobby {...{ name, setName, joinCode, setJoinCode, enterRoom, hasSupabase }} />
  if (view === 'room') return <Room {...{ players, roomCode, isHost, startGame, leave, hasSupabase }} />
  return <Game {...{ players, me, roomCode, round, phase, seconds, choice, setChoice, locked, lock, summary, nextRound, leave, gameOver, setGameOver, hasSupabase }} />
}

function Lobby({ name, setName, joinCode, setJoinCode, enterRoom, hasSupabase }) { return <main className="lobby-shell"><div className="noise" /><header className="topline"><div className="brand-mark"><span>♦</span> KING OF DIAMONDS</div><div className="system-state"><span className="pulse-dot" /> SYSTEM ONLINE / 00:00:00</div></header><section className="lobby-hero"><div className="hero-copy"><p className="eyebrow"><Crosshair size={14} /> A MULTIPLAYER SURVIVAL PROTOCOL</p><h1>BALANCE<br /><em>OR BREAK.</em></h1><p className="hero-lede">Five minds. One target. Every number is a wager against the crowd.</p><div className="hero-rule"><span /> THE SCALE DOES NOT FORGIVE <span /></div></div><div className="terminal-panel"><div className="panel-head"><span>PLAYER IDENTIFICATION</span><span className="panel-code">AUTH // 01</span></div><label className="field-label" htmlFor="player-name">YOUR DESIGNATION</label><input id="player-name" value={name} onChange={(event) => setName(event.target.value)} placeholder="ENTER PLAYER NAME" maxLength={18} /><button className="primary-action" onClick={() => enterRoom(true)}><Sparkles size={17} /> CREATE NEW ROOM <ChevronRight size={17} /></button><div className="or-line"><span /> OR JOIN EXISTING <span /></div><div className="join-row"><input value={joinCode} onChange={(event) => setJoinCode(event.target.value.replace(/\D/g, '').slice(0, 6))} placeholder="000 000" inputMode="numeric" /><button className="join-action" onClick={() => enterRoom(false)}><DoorOpen size={17} /> JOIN</button></div><div className="connection-note">{hasSupabase ? <><Wifi size={13} /> REALTIME CHANNEL READY</> : <><WifiOff size={13} /> PREVIEW MODE · ADD SUPABASE ENV TO DEPLOY</>}</div></div></section><footer className="lobby-footer"><span><ShieldAlert size={14} /> PLAY RESPONSIBLY. THE HOUSE ALWAYS COUNTS.</span><span>PROTOCOL 0.8 // BUILD 2026.09</span></footer></main> }

function Room({ players, roomCode, isHost, startGame, leave, hasSupabase }) { return <main className="room-shell"><header className="topline"><div className="brand-mark"><span>♦</span> KING OF DIAMONDS</div><button className="text-action" onClick={leave}><LogOut size={15} /> EXIT ROOM</button></header><section className="room-content"><div className="room-intro"><p className="eyebrow"><Users size={14} /> WAITING ROOM</p><h1>THE TABLE<br /><em>IS SET.</em></h1><p>Share the code. When the room is full of courage, the host may begin.</p></div><div className="room-code"><span>ROOM CODE</span><strong>{roomCode.slice(0, 3)} <b>{roomCode.slice(3)}</b></strong><button onClick={() => navigator.clipboard?.writeText(roomCode)}><Copy size={15} /> COPY CODE</button></div><div className="roster-head"><span>CONNECTED PLAYERS</span><strong>{players.length.toString().padStart(2, '0')} / 05</strong></div><div className="roster">{[0, 1, 2, 3, 4].map((slot) => { const player = players[slot]; return <div className={`roster-row ${player ? 'occupied' : ''}`} key={player?.id ?? slot}><span className="slot-number">0{slot + 1}</span><span className="avatar">{player ? player.name[0].toUpperCase() : '—'}</span><span className="roster-name">{player?.name ?? 'AWAITING PLAYER'}</span>{slot === 0 && player && <span className="host-tag">HOST</span>}<span className="roster-status">{player ? 'READY' : 'OPEN'}</span></div> })}</div><div className="room-bottom"><div><Radio size={15} /> {hasSupabase ? 'BROADCAST ENCRYPTED' : 'LOCAL PREVIEW CHANNEL'}<br /><small>Max 5 players · first entrant is host</small></div>{isHost ? <button className="primary-action start-button" onClick={startGame}><Zap size={17} /> START THE GAME <ChevronRight size={17} /></button> : <div className="waiting-host"><Activity size={16} /> WAITING FOR HOST TO BEGIN</div>}</div></section></main> }

function Game({ players, me, roomCode, round, phase, seconds, choice, setChoice, locked, lock, summary, nextRound, leave, gameOver, setGameOver, hasSupabase }) { return <main className="game-shell"><div className="noise" /><header className="game-header"><div className="brand-mark"><span>♦</span> KING OF DIAMONDS</div><div className="header-meta"><span>ROOM <b>{roomCode}</b></span><span>ROUND <b>{String(round).padStart(2, '0')}</b></span><span className="live-indicator"><span className="pulse-dot" /> {hasSupabase ? 'LIVE' : 'PREVIEW'}</span><button className="icon-action" title="Leave room" onClick={leave}><LogOut size={16} /></button></div></header><section className="game-main"><div className="game-title-row"><div><p className="eyebrow"><Activity size={14} /> {phase === 'lock' ? 'SELECTION PHASE' : phase === 'reveal' ? 'REVEALING NUMBERS' : 'ROUND COMPLETE'}</p><h1>FIND THE<br /><em>WEIGHT.</em></h1></div><div className={`countdown ${seconds <= 10 ? 'critical' : ''}`}><span>LOCK WINDOW</span><strong>00:{String(seconds).padStart(2, '0')}</strong><div className="timer-line"><i style={{ width: `${seconds / ROUND_SECONDS * 100}%` }} /></div></div></div><div className="players-grid">{players.map((player, index) => <Card key={player.id} player={player} index={index} me={me} />)}</div><div className="control-row"><div className="protocol-note"><LockKeyhole size={16} /><div><strong>CHOOSE IN SECRET</strong><span>Your number stays sealed until every player locks.</span></div></div><div className="choice-panel"><label htmlFor="choice">YOUR NUMBER</label><div className="choice-input"><input id="choice" type="number" min="0" max="100" value={choice} disabled={locked || me?.dead || phase !== 'lock'} onChange={(event) => setChoice(event.target.value)} /><span>/ 100</span></div><input className="range" type="range" min="0" max="100" value={choice} disabled={locked || me?.dead || phase !== 'lock'} onChange={(event) => setChoice(event.target.value)} /><button className={`lock-button ${locked ? 'is-locked' : ''}`} onClick={lock} disabled={locked || me?.dead || phase !== 'lock'}>{locked ? <><LockKeyhole size={17} /> NUMBER SEALED</> : <><LockKeyhole size={17} /> LOCK NUMBER</>}</button></div></div>{phase === 'reveal' && <div className="reveal-strip"><Zap size={15} /> All numbers are being decrypted. The scale is calculating.</div>}</section>{summary && <Summary summary={summary} nextRound={nextRound} alive={players.filter((player) => !player.dead).length} />}{gameOver && <div className="game-over"><div className="game-over-grid" /><Flame size={46} /><p>PROTOCOL TERMINATED</p><h2>GAME OVER</h2><strong>ACID SCALE TILTED</strong><button className="primary-action" onClick={() => setGameOver(false)}>ACKNOWLEDGE <ChevronRight size={17} /></button></div>}</main> }
function Card({ player, index, me }) { const acid = Math.min(100, Math.abs(player.points) * 10); return <article className={`player-card ${player.dead ? 'dead' : ''} ${player.id === me?.id ? 'self' : ''}`}><div className="card-top"><span className="player-index">0{index + 1}</span><span className={`status ${player.dead ? 'dead-status' : player.locked ? 'locked-status' : ''}`}>{player.dead ? <><Skull size={12} /> DEAD</> : player.locked ? <><LockKeyhole size={12} /> LOCKED</> : <><span className="tiny-dot" /> CHOOSING</>}</span></div><div className="player-avatar">{player.dead ? <Skull size={25} /> : player.name[0].toUpperCase()}</div><h2>{player.name}{player.id === me?.id && <small>YOU</small>}</h2><div className="points-readout"><span>POINTS</span><strong>{String(player.points).padStart(2, '0')} <i>/ -10</i></strong></div><div className="acid-bar"><span style={{ height: `${acid}%` }} /></div><div className="card-footer"><span>ACID LOAD</span><b>{acid}%</b></div></article> }
function Summary({ summary, nextRound, alive }) { return <div className="overlay"><section className="summary-modal"><div className="modal-kicker"><span>ROUND {String(summary.round).padStart(2, '0')} // DECRYPTED</span><span><Activity size={14} /> RESULT</span></div><h2>THE SCALE<br /><em>HAS SPOKEN.</em></h2><div className="result-metrics"><div><span>AVERAGE</span><strong>{summary.average.toFixed(1)}</strong></div><div className="target-metric"><span>TARGET × 0.8</span><strong>{summary.target.toFixed(1)}</strong></div><div><span>WINNER</span><strong>{summary.winnerName}</strong></div></div><div className="numbers-table"><div className="table-head"><span>PLAYER</span><span>CHOICE</span><span>DELTA</span></div>{summary.players.map((player) => <div className="table-row" key={player.id}><span>{player.name}</span><span>{summary.choices[player.id]}</span><span className={summary.penalties[player.id] === 0 ? 'win-delta' : 'loss-delta'}>{summary.penalties[player.id] === 0 ? '+ WIN' : summary.penalties[player.id]}</span></div>)}</div><div className="modal-footer"><span>{alive <= 1 ? 'FINAL CALCULATION' : 'NEXT ROUND READY'}</span><button className="primary-action" onClick={nextRound}>{alive <= 1 ? 'VIEW OUTCOME' : 'CONTINUE'} <ChevronRight size={17} /></button></div></section></div> }
